#!/bin/bash

# install brew
# ref: https://brew.sh/
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install brews
brew bundle "$HOME/.dotfiles-local/Brewfile"

# install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.6.2

# install asdf-nodejs
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

# install asdf-ruby
asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

# install yarn
curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
