#
# Aliases
#

dotfiles=$HOME/.dotfiles

alias v='mvim'

# Editing config files
alias ve='v $dotfiles/vim/vimrc'
alias ze='v $dotfiles/zsh/zshrc'
alias zpe='v $HOME/.zpreztorc'

# Reload settings
alias zr='source $dotfiles/zsh/zshrc'

# Show me the aliases
alias sal='p $dotfiles/zsh/zshrc | ag --nocolor "alias " && ag --nocolor "alias " $HOME/.zprezto/modules'

# Show me files matching "ls ag"
alias lsf='ll | ag'

# PS
alias psa='ps aux'
alias psg='ps aux | ag '
alias psr='ps aux | ag ruby'

# Common shell functions
alias tf='tail -f'
alias lh='ls -alt | head' # see the last modified files
alias cl='clear'

# Zippin
alias gzc='tar -zcvf'
alias gzx='tar -zxvf'

# Kill
alias ka9='killall -9'
alias k9='kill -9'

# Git
alias gfa='p $HOME/.zprezto/modules/git/alias.zsh | ag --nocolor '
alias gsuo='gfm upstream master && gwR upstream master && gp origin master'
